// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRbos-m9BLMQFaK-nAafAi_BGPGIDvNg',
    appId: '1:1006454812188:android:3e5d7908b377359194f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    storageBucket: 'rewardly-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXT-6Teaw4_wyPuPz-j5nEYA8AcLP3jbo',
    appId: '1:1006454812188:ios:4d22aaf34600c29894f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    storageBucket: 'rewardly-new.firebasestorage.app',
    iosBundleId: 'com.supreet.rewardly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNmCsyoXUTZQcwQZjgqr3JxdUMqpfAsMc',
    appId: '1:1006454812188:web:331704ea9d8b223d94f9d9',
    messagingSenderId: '1006454812188',
    projectId: 'rewardly-new',
    authDomain: 'rewardly-new.firebaseapp.com',
    storageBucket: 'rewardly-new.firebasestorage.app',
  );

}